### ISSUE TITLE
[deleted]

### ISSUE THREAD

**Issue by Imperat** [mhagmajer/server-router#1]

**Comment by mhagmajer** [comment]
Thanks for posting an issue @Imperat. First of all, please check out my blog post about using this package, if you haven't already: https://blog.hagmajer.com/server-side-routing-with-authentication-in-meteor-6625ed832a94.

`WebApp` is a built-in package in Meteor that let's you add more middleware to server processing of web requests. You can learn more about it at https://docs.meteor.com/packages/webapp.html. All you need to do is to hook up server router's middleware with webapp like so:

```js
const serverRouter = new ServerRouter();
WebApp.connectHandlers.use(serverRouter.middleware);
```

The reasen why package doesn't do it itself is to leave you the choice of ordering of the middleware.

Following up on your example, if you have a single path set up:

```js
serverRouter.addPath({
  path: '/binary-representation/:n',
  args: ({ n }) => [Number(n)],
  async route(n) {
    this.res.end(n.toString(2));
  },
});
```

You can just do the regular redirects from the client:

```html
<a href="/binary-representation/42/">See binary representation of 42</a>
```

The `path` and `redirect` properties of `ServerRouterClient` are useful if you use special kind of paths - routes. You can find out more about this in the blog post.

Please do comment on the issue if you have more questions. I'm happy to help and update the docs as required.

**Comment by Imperat** [comment]
Sorry, 2 minutes ago I was tryed to delete my issue thats why I have researched about WebApp. 
If your have ability I would like to ask your about routes. 
Now in server-side of my application I have implemented around 10 endpoints via 

```
serverRouter.addPath({
  path: '/teams/export/global/',
  args: (params, query) => [query.date],
  async route(date) {
    const data = generateTeamsLogs(date);
    this.res.writeHead(200, {
      'Content-Type': 'application/csv',
      'Content-disposition': `attachment; filename=teams-logs-${date}.csv`,
    });

    this.res.end(data);
  },
});
```

I can use this endpoint in client such as:
```
serverRouterClient.redirectTo('/teams/export/global/');
```

My next question: is there any ability to add names for endpoints? for example in server I can add name "exportGlobalTeams", and in client use it like this:
```
serverRouterClient.redirectTo('exportGlobalTeams')
```

I know about this mechanics is used in Django framework:
```
url(r'^player/', views.PlayersListView.as_view(), name='players')
```

and it's used in templates such as:

```
{% url 'players' %}
```

**Comment by Imperat** [comment]
Thanks for you answer! It's really happy to get feed back from open source developers :)

**Comment by mhagmajer** [comment]
I think what you need are routes. They abstract from the actual path giving
you ability to redirect users by using the name of the route only. There is
couple of examples in the blog post on this.

You can have the same function used as a path and as a route. The first
case is identified as url path and the second by the name of the route.

Let me know if this helped.

**Comment by Imperat** [comment]
Sorry, I'm really missunderstanding how I can add route name to my path in above snippet. May be you can provide me some snippet how I can use same function for route and path?
I think it may be convenient if in client code I'll use name of route, and also I'll have ability to configure good  urls paths.

**Comment by Imperat** [comment]
Also I have good question: that is good way to throw AutheticationRequired error? In docs you have only one note about this: 'Thrown by routes when authentication is required for further processing.'

**Comment by Imperat** [comment]
Sorry for many spam and questions :) I need to migrate large codebase from Picker to you package because of security issues

**Comment by mhagmajer** [comment]
Michael, did you read the blog post? :)

**Comment by Imperat** [comment]
Of course, but may be today I'm a bit disperse :)

**Comment by mhagmajer** [comment]
Route is basically just a function. You can use it with `addPath` like you
did correctly but also you can use it with `addRoute`. The latter lets the
client use simpler methods to redirect users to the route.

The `AuthenticationRequiredError` causes the client to fetch token needed
by the route and redirects to it again.

We've migrated away from Picker gor the same reason with good success. I'm
happy to help you along the way!

**Comment by Imperat** [comment]
I understand differences between routes and paths!
Thank you for you support)

**Comment by mhagmajer** [comment]
Please know if I can help any further. I'd  like you to be happy with this
package!

**Comment by Imperat** [comment]
Of course, Marcin!
I have small question for future: have you any others interesting open source project? Sometimes I relax with contributing in github :)

**Comment by mhagmajer** [comment]
I'm currently working on adding GraphQL support to Meteor. This will be the
next open source package that I release. Publications in Meteor have
certain limitations that GraphQL addresses well. I'll let you know once
that is released.

You're more than welcome to contribute to this project - features or
documentation. I'll review any PRs as soon as I can.
