### ISSUE TITLE
crashing on meteor add

### ISSUE THREAD

**Issue by marcpmichel** [mhagmajer/server-router#5]
On windows, trying to add the package crashes with the following error.
Works as expected on linux.
Tested on a working Meteor 1.6.0.1 app we are working on and on a brand new Meteor 1.6.1 app :

```
meteor add mhagmajer:server-router
C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\xxx\AppData\Local\Temp\mt-1l8591f.zq4xl\os\definitions\flow_v0.46.x\mhagmajer:server-router_v1.x.x.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.wrapper [as open] (C:\tools\fs\files.js:1564:35)
...
```

**Comment by mhagmajer** [comment]
Hi @marcpmichel, thanks for reporting the issue!

I was able to confirm that package installs okay on Meteor 1.6.1 and Mac OS. This makes me think that this issue might be better addressed by the Meteor community itself at https://github.com/meteor/meteor/issues. Would you mind posting your issue there? That might be related some incorrect handling of file names on Windows by Meteor package manager.

**Comment by marcpmichel** [comment]
Done.
Thanks for the quick reply !
